config/routes.rb
Rails.application.routes.draw do
  
  resources :datos, as: :facts, controller: :facts
  root to: "home#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/dateable.rb
module Dateable
  extend ActiveSupport::Concern

  def created_at_format
    meses = ["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"]
    mes = meses[created_at.strftime("%-m").to_i - 1]
    dia = created_at.strftime("%d")
    year = created_at.strftime("%Y")
    
    "#{dia} de #{mes} del #{year}"
  end

end

app/models/fact.rb
# == Schema Information
#
# Table name: facts
#
#  id          :integer          not null, primary key
#  title       :string(50)
#  description :string(250)
#  real        :boolean
#  color       :string(255)
#  code        :string(255)
#  resource    :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Fact < ApplicationRecord

  include Dateable

  attr_accessor :labels

  validates :labels, presence: true
  validates :title, presence: true
  validates :description, presence: true

  before_create :set_color
  before_create :set_code
  after_save :create_fact_tags

  has_many :fact_tags, dependent: :destroy
  has_many :tags, through: :fact_tags, source: :tag

  def labels_format
    (tags.any?) ? tags_format : ''
  end

  def tags_format(str='', prefix=',')
    tags.each { |tag| str = str + " " + tag.title + prefix }
    str.strip[0..-2]
  end

  private
    def create_fact_tags
      labels.split(',').each { |tag| create_fact_tag(tag) } #Label is a attr_accessor
    end

    def create_fact_tag(tag='')
      FactTag.create_by_fact_tags(self, Tag.get_or_create_by_title(tag))
    end

    def generate_code
      SecureRandom.uuid
    end

    def set_code
      self.code = generate_code
    end

    def set_color
      self.color ||= '#' + SecureRandom.hex(3)
    end

end

app/models/fact_tag.rb
# == Schema Information
#
# Table name: fact_tags
#
#  id         :integer          not null, primary key
#  fact_id    :integer
#  tag_id     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class FactTag < ApplicationRecord
  belongs_to :fact
  belongs_to :tag

  validates :fact, presence: true
  validates :tag, presence: true

  def self.create_by_fact_tags(fact, tag)
    find_or_create_by(fact: fact, tag:tag)
  end
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tag < ApplicationRecord

  validates :title, presence: true
  
  def self.get_or_create_by_title(title)
    find_or_create_by(title: Tag.title_format(title))
  end

  def self.title_format(title)
    title.strip.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
  before_action :set_fact, only: [:show, :edit, :update, :destroy]

  def index
    @facts = Fact.all
  end

  def show
  end

  def new
    @fact = Fact.new
  end

  def edit
  end

  def create
    @fact = Fact.new(fact_params)
    respond_to do |format|
      if @fact.save
        format.html { redirect_to facts_path, notice: 'Dato generado exitosamente' }
        format.json { render :show, status: :created, location: @fact }
      else
        format.html { render :new }
        format.json { render json: @fact.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @fact.update(fact_params)
        format.html { redirect_to @fact, notice: 'Dato actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @fact }
      else
        format.html { render :edit }
        format.json { render json: @fact.errors, status: :unprocessable_entity }
      end
    end
  end
    
  def destroy
    @fact.destroy
    respond_to do |format|
      format.html { redirect_to facts_url, notice: 'Dato eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    
    def set_fact
      @fact = Fact.find(params[:id])
    end
        
    def fact_params
      params.require(:fact).permit(:title, :description, :real, :color, :code, :resource, :labels)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/facts/_form.html.erb
<%= form_with(model: fact, local: true) do |form| %>
  <% if fact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fact.errors.count, "error") %> prohibited this fact from being saved:</h2>

      <ul>
      <% fact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title, id: :fact_title, placeholder:"Título", class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.text_field :description, id: :fact_description, class:"form-control", placeholder:"Descripción" %>
  </div>

  <div class="form-group">
    <%= form.text_field :labels, id: :fact_labels, placeholder:"Tags", class:"form-control", value: @fact.labels_format %>
  </div>

  <div class="form-check">
    <%= form.check_box :real, id: :fact_real, class:"form-check-input"%>
    <label class="form-check-label" for="real">Real</label>
  </div>
  
  <div class="form-group">
    <%= form.text_field :resource, id: :fact_resource, placeholder:"Recurso", class:"form-control" %>
  </div>
  
  <div class="actions">
    <button type="submit" class="btn btn-sb"> <%= action %></button>
  </div>
<% end %>

app/views/facts/edit.html.erb
<div class="container">
  <br>
  <h1>Editar dato</h1>

  <%= render 'form', fact: @fact, action: "Editar" %>

</div>

app/views/facts/index.html.erb
<div class="container">
  
  <p id="notice"><%= notice %></p>

  <h2>Datos</h2>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Título</th>
        <th>Decripción</th>
        <th>Real</th>
        <th>Color</th>
        <th>Código</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @facts.each do |fact| %>
        <tr>
          <td><%= fact.title.truncate 20, omission:"..." %></td>
          <td><%= fact.description.truncate 20, omission:"..." %></td>
          <td><%= fact.real %></td>
          <td><%= fact.color %></td>
          <td><%= fact.code %></td>
          <td><%= link_to 'Mostrar', fact %></td>
          <td><%= link_to 'Editar', edit_fact_path(fact) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Nuevo dato', new_fact_path, class:"btn btn-sb" %>

</div>

app/views/facts/new.html.erb
<div class="container">
  <br>
  <h1>Nuevo dato!</h1>

  <%= render 'form', fact: @fact, action:"Crear" %>

</div>

app/views/facts/show.html.erb
<div class="container">
  <br>
  <div class="card text-center">
    <div class="card-header">
      <%= @fact.code %>
    </div>
    <div class="card-block">
      
      <h4 class="card-title"> <%= @fact.title %></h4>
      <p class="card-text"> <%= @fact.description %> </p>
      
      <%= link_to 'Editar', edit_fact_path(@fact), class:"btn btn-primary"%>
      <%= link_to 'Eliminar', @fact, method: :delete, data: { confirm: '¿Estas seguro de eliminar el dato?' }, class:"btn btn-danger" %>
      
    </div>
    <br>
    <div class="card-footer text-muted">
     Fecha de creación: <%= @fact.created_at_format %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container">
  
  <h1>¯\_(ツ)_/¯</h1>
  <p>Algún día pondré algo </p>

</div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sabias que</title>

    <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
     <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #1c2b3a;">
      <div class="container">
        <a class="navbar-brand-sb" href="<%= root_path %>">Sabias que!</a>

        <button class="navbar-toggler navbar-toggler-right custom-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">

        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            
            <li class="nav-item active">
              <a class="nav-link-sb" href="<%= facts_path %>">Datos</a>
            </li>
          </ul>

          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a href="" class="btn nav-link-sb">Iniciar sessión</a>
            </li>
          
            <li class="navbar-item">
              <button class="btn nav-btn-sb type="submit">Registrarse</button>
            </li>
          </ul>

        </div>
       </div> 
    </nav>

    <%= yield %>  

  </body>
</html>